### ISSUE TITLE
 请问是否有tf2重构的打算？

### ISSUE THREAD

**Issue by DachuanZhao** [ZhaoLiang-GitHub/GraphEmbedding-TransX#2]
如题，请问是否有用tf2重构的打算？可以一起哈～

**Comment by ZhaoLiang-GitHub** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    感谢，graphembedding有两个仓库，transx和深度学习的两套思路，之前考虑过用tf2重构，由于工作比较忙就停下了，如果您感兴趣我们可以一起开发
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                赵亮
                            
                    
                        
                            
                                    1318525510@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年12月17日 11:43，DachuanZhao<notifications@github.com> 写道： 


如题，请问是否有用tf2重构的打算？可以一起哈～



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DachuanZhao** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 感谢，graphembedding有两个仓库，transx和深度学习的两套思路，之前考虑过用tf2重构，由于工作比较忙就停下了，如果您感兴趣我们可以一起开发 赵亮 1318525510@qq.com 签名由 网易邮箱大师 定制 在2019年12月17日 11:43，DachuanZhao<notifications@github.com> 写道： 如题，请问是否有用tf2重构的打算？可以一起哈～ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

您好，我看了以下您的代码，transD的负样本的构造得请教一下。原文中是只替换了 h 或者 t，而您的代码里是直接随机选了(h ,r ,t)，请问是有什么tricks么？n(*≧▽≦*)n

**Comment by ZhaoLiang-GitHub** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    见字如面：在这随机选择hrt，目的就是来增加负样本的混乱程度，测试过这样效果更好（我感觉就是我的图谱结构比较简单，关系类别和实体类别很少，如果只是替换一个，达不到增加负样本的效果）一点拙见，期待与您进一步沟通，祝一切都好！
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                赵亮
                            
                    
                        
                            
                                    1318525510@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年12月18日 20:16，DachuanZhao<notifications@github.com> 写道： 



font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 感谢，graphembedding有两个仓库，transx和深度学习的两套思路，之前考虑过用tf2重构，由于工作比较忙就停下了，如果您感兴趣我们可以一起开发 赵亮 1318525510@qq.com 签名由 网易邮箱大师 定制 在2019年12月17日 11:43，DachuanZhaonotifications@github.com 写道： 如题，请问是否有用tf2重构的打算？可以一起哈～ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

您好，我看了以下您的代码，transD的负样本的构造得请教一下。原文中是只替换了 h 或者 t，而您的代码里是直接随机选了(h ,r ,t)，请问是有什么tricks么？n(≧▽≦)n

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DachuanZhao** [comment]
重写完了transD，因为tf2改动太大，只能另起炉灶，有时间还请雅正一下哈

**Comment by DachuanZhao** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 见字如面：在这随机选择hrt，目的就是来增加负样本的混乱程度，测试过这样效果更好（我感觉就是我的图谱结构比较简单，关系类别和实体类别很少，如果只是替换一个，达不到增加负样本的效果）一点拙见，期待与您进一步沟通，祝一切都好！ 赵亮 1318525510@qq.com 签名由 网易邮箱大师 定制 在2019年12月18日 20:16，DachuanZhao<notifications@github.com> 写道： font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 感谢，graphembedding有两个仓库，transx和深度学习的两套思路，之前考虑过用tf2重构，由于工作比较忙就停下了，如果您感兴趣我们可以一起开发 赵亮 1318525510@qq.com 签名由 网易邮箱大师 定制 在2019年12月17日 11:43，DachuanZhaonotifications@github.com 写道： 如题，请问是否有用tf2重构的打算？可以一起哈～ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 您好，我看了以下您的代码，transD的负样本的构造得请教一下。原文中是只替换了 h 或者 t，而您的代码里是直接随机选了(h ,r ,t)，请问是有什么tricks么？n(≧▽≦)n —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

重写完了transD，因为tf2改动太大，只能另起炉灶，有时间还请雅正一下哈

**Comment by ZhaoLiang-GitHub** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    见字如面：看到了request了，稍后查看下pull下，您辛苦，期待与您进一步沟通
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                赵亮
                            
                    
                        
                            
                                    1318525510@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年12月19日 18:07，DachuanZhao<notifications@github.com> 写道： 


重写完了transD，因为tf2改动太大，只能另起炉灶，有时间还请雅正一下哈



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
